### ISSUE TITLE
没法同步了…… 显示404error

### ISSUE THREAD

**Issue by rickyking** [fuergaosi233/wereadwise#4]
![CleanShot 2023-04-25 at 23 26 05@2x](https://user-images.githubusercontent.com/2820809/234487882-0baa8f8f-413c-4498-9da6-55bbab2b57b2.png)

**Comment by Xinnerpeace** [comment]
Same😭

**Comment by pictureye** [comment]
me too

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wereadwise/pull/5 Fixed

**Comment by rickyking** [comment]
好像还是没有办法同步哦
